return {
  ["AWP"] = true,
  ["Hydrogen"] = true,
  ["Potassium"] = true,
  ["Swift"] = true,
  ["Codex"] = true,
  ["Solara"] = true,
  ["Delta"] = true,
  ["Volt"] = true,
  ["Wave"] = true,
  ["Velocity"] = true,
  ["Seliware"] = true,
  ["Bunni"] = true,
  ["Zenith"] = true,
  ["Arceus X"] = true,
  ["Xeno"] = true,
}
