return {
  ["AWP"] = true,
  ["Hydrogen"] = true,
  ["Potassium"] = true,
  ["Swift"] = true,
  ["Codex"] = true,
  ["Solara"] = true,
  ["Delta"] = true,
  ["Cosmic"] = true,
  ["Volt"] = true,
  ["Synapse Z"] = true,
  ["MacSploit"] = true,
  ["Wave"] = true,
  ["Nihon"] = true,
  ["Velocity"] = true,
  ["Seliware"] = true,
  ["Bunni"] = true,
  ["Zenith"] = true,
  ["Arceus X"] = true,
  ["Xeno"] = true,
}
